experiment:
  name: AP 1              # The name of experiment.
  log_dir: results/APCNN  # Log directory of the experiment.
  cuda: [0]               # The list of gpu to use. `[]` for cpu only.
  seed: 42                # Fix the random seed. `None` for random.
dataset:
  name: Mosquito
  root_dir: data/dataset_mosquito
  meta_dir: metadata/dataset_mosquito
  batch_size: 24
  num_workers: 2
  transformer:
    image_size: 224
    resize_size: 300
model:
  name: APCNN
  num_classes: 3
train:
  epoch: 100
  save_frequence: 100
  optimizer:
    name: SGD
    lr: 0.0005
    weight_decay: 0.0005
  scheduler:
    name: origin_code
  criterion:
    name: CrossEntropyLoss

