experiment:
  name: CBCNN 1
  log_dir: results/CBCNN
  cuda: [0]
  seed: 0
dataset:
  name: Mosquito
  root_dir: data/dataset_mosquito
  meta_dir: metadata/dataset_mosquito
  batch_size: 24
  num_workers: 4
  transformer:
    image_size: 224
    resize_size: 300
model:
  name: CBCNN
  stage: 1  # Training stage for CBCNN. We freeze backbone parameters in stage 1.
  num_classes: 3
  input_channel: 512    # Input dimension of compact bilinear pooling.
  output_channel: 6000  # Output dimension of compact bilinear pooling.
train:
  epoch: 120
  save_frequence: 120
  optimizer:
    name: SGD
    lr: 2.0
    momentum: 0.9
    weight_decay: 0.00000001
  scheduler:
    T_max: 120
    warmup_epochs: 5
    lr_warmup_decay: 0.01
  criterion:
    name: CrossEntropyLoss
