experiment:
  name: D 1
  log_dir: results/DCL
  cuda: [0]
  seed: 42
dataset:
  name: Mosquito
  root_dir: data/dataset_mosquito
  meta_dir: metadata/dataset_mosquito
  batch_size: 24
  num_workers: 0
  transformer:
    image_size: 224
    resize_size: 300
model:
  name: DCL
  num_classes:  3
  cls_2: True
  cls_2xmul: False
train:
  epoch: 180
  save_frequence: 60
  optimizer:
    name: SGD
    lr: 0.0008
    lr_ratio: 10
    weight_decay: 0.00002
    momentum: 0.9
  scheduler:
    name: StepLR
    step_size: 60
    gamma: 0.1
  criterion:
    name: DCLLoss
    alpha: 1  # Alpha in Eq.(10), balancing different loss.
    beta: 1   # beta in Eq.(10), balancing different loss.
    gamma: 1  # gamma in Eq.(10), balancing different loss.

