experiment:
  name: PL_BCNN 1
  log_dir: results/PeerLearning
  cuda: [0]
  seed: 0
dataset:
  name: Mosquito
  root_dir: data/dataset_mosquito
  meta_dir: metadata/dataset_mosquito
  batch_size: 24
  num_workers: 0
  transformer:
    image_size: 224
    resize_size: 300
model:
  name: PeerLearningNet
  base_model:         # PeerLearningNet contains two identical models. Here it uses a Bilinear CNN.
    name: BCNN
    stage: 1
    num_classes: 3
  drop_rate: 0.35     # The maximum drop rate, `\xi` in Eqn.(2).
  T_k: 10             # The number of epochs after which d(T) is no longer updated, `T_k` in Eqn.(2).
train:
  epoch: 200
  save_frequence: 50
  optimizer:
    name: Adam
    lr: 0.0001
    weight_decay: 0.00000001
    momentum: 0.9
  scheduler:
    name: ''
    T_max: 200
    warmup_epochs: 10
    lr_warmup_decay: 0.01
  criterion:
    name: PeerLearningLoss
